services:
  api:
    restart: no
    build:
      context: ../backend/
    ports:
      - "5000:8080"
    env_file:
      - .env.dev
    depends_on:
      - database

  frontend:
    restart: no
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.dev

  database:
    image: postgres:18
    restart: no
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: portfolio_db
    ports:
      - "5433:5432"
    volumes: []
