name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # build
        
      - name: Build Backend Docker image
        run: |
          docker build -t ghcr.io/nexx42/backend:${{ github.sha }} ./backend

      - name: Build Frontend Docker image
        run: |
          docker build -t ghcr.io/nexx42/frontend:${{ github.sha }} ./frontend
          
      # push  
        
      - name: Push Backend Docker image
        run: |
          docker push ghcr.io/nexx42/backend:${{ github.sha }}

      - name: Push Frontend Docker image
        run: |
          docker push ghcr.io/nexx42/frontend:${{ github.sha }}
          
      #- name: Deploy to server
      #  uses: appleboy/ssh-action@v0.1.6
      #  with:
      #    host: ${{ secrets.SERVER_IP }}
      #    username: ${{ secrets.SERVER_USER }}
      #    key: ${{ secrets.SERVER_SSH_KEY }}
      #    script: |
      #      ~/apps/portfolio/deploy.sh ${{ github.sha }}